Vungle/vungo

.travis.yml
CONTRIBUTING.md
README.md

Adds Travis CI, README, and CONTRIBUTING.

chore(setup): Adds CI, README, and CONTRIBUTING docs.

---

.travis.yml
README.md

Adds Travis CI build status icon.

chore(setup): Add Travis build status icon.

---

openrtbutil/client_test.go
testdata/bidrequest.json
testdata/impression.json
testdata/video.json
video.go

- Also, fixes some intermittencies in openrtbutil tests.
Fixes Vungle/jaeger#546.

fix(openrtb): Video object field playbackmethods should be playbackmethod

---

openrtb/openrtbutil/client.go

feat(openrtbutil): Increase HTTP client timeout to 10 seconds

---

.gitignore
.travis.yml
CONTRIBUTING.md
README.md

- Updates README, CONTRIBUTING
- Updates travis to run against 1.7 as basis
- Updates gitignore

Ops updates 

---

README.md

docs(ops): adds godoc badge

---

openrtb/bidresponse.go
openrtb/impression.go
openrtb/openrtbtest/testutil.go
openrtb/openrtbutil/example_test.go

This reverts commit 74cad208bc1df709e7b947be0dd7c6d31d49d9f2

revert: Update to make price floors optional

---

openrtb/impression.go
openrtb/testdata/impression.json

----Open RTB V2----
Adds field secure so we can start populating it

feat(impression): include secure field in impressions

---

openrtb/os.go

Introduces a new os type `amazon`

feat(os): Adds amazon support

---

vast/ad_test.go
vast/companion.go
vast/companion_test.go
vast/companionads_test.go
vast/companionadswrapper_test.go
vast/companionwrapper.go
vast/companionwrapper_test.go
vast/errors.go
vast/htmlresource.go
vast/htmlresource_test.go
vast/icon.go
vast/icon_test.go
vast/nonlinear.go
vast/nonlinear_test.go
vast/vastutil/validationresult.go

More clean up of over validation on VAST.

fix(vast): remove over validation.

---

vast/nonlinear.go

Add a check for the pointer before doing validation on the field.

fix(vast): Check pointer before doing validation.

---

vast/inline_test.go
vast/pricing.go
vast/pricing_test.go

Remove the validation for pricing model and currency.

feat(vast):Remove the validation for pricing model and currency.

---

vast/linear.go
vast/linear_test.go
vast/mediafile.go
vast/mediafile_test.go
vast/testdata/invalid_mediafiles_with_invalid_mimetype.xml
vast/testdata/linear_at_least_one_invalid_mediafile.xml
vast/vasttest/vasttest.go

Fix the error messages . for media file validation.

fix(vast): Fix error message for media file validation.

---

go.mod
go.sum

support go module

---

openrtb/lossreason.go
openrtb/macrosubs.go
openrtb/macrosubs_bench_test.go
openrtb/macrosubs_test.go

The PR add the LossReason in the openrtb

feat(openrtb): add Loss reason

---

vast/mediafile.go

Revert "Use filepath api instead of regex when validate uri of mediafile."

---

vast/linear.go

Fix the error message when the media file is invalid

fix mimetype error for media file

---

openrtb/apiframework.go

Revert "Add  OMID API frameworks support."

---

openrtb/auctioninfo.go
openrtb/macrosubs.go
openrtb/macrosubs_test.go

Update settlement interface name to make it work for both win and loss notification.

feat(lurl)[PBJ-2035]: to support loss notification

---

openrtb/auctioninfo.go
openrtb/errors.go
openrtb/macrosubs.go
openrtb/macrosubs_test.go
openrtb/seatbid.go
openrtb/seatbid_test.go

Add support for AUCTION_MIN_TO_WIN

feat(openrtb):add support to AUCTION_MIN_TO_WIN

---

openrtb/errors.go
openrtb/seatbid.go

Fix panic if there is nil bid in seat bid

fix(panic)[PBJ-XXXX]: fix panic if there is nil bid in seat bid

---

vast/vastelement/companion.go
vast/vastelement/linear.go
vast/vastelement/mediafile.go
vast/vastelement/testdata/companion.xml
vast/vastelement/testdata/linear.xml
vast/vastelement/testdata/mediafile.xml

This PR will add alternative attr for `Linear` and `Companion`.

feat(vastelement): Add alternative attr for linear and companion.

---

openrtb/connectiontype.go

add a new connection type for OpenRTB update.

feat(connectiontype)[PBJ-6854] standardization device connection type 

---

openrtb/lossreason.go

Add new Loss reason code for bid price that exceed the max value.

feat(openrtb)[PBJ-7103]:add new loss reason code for bid max

---

vast/vastelement/linear.go
vast/vastelement/testdata/linear.xml

This PR add id attr for linear element.

feat(vastelement): Ad id attr for linear element.

---

vast/vastelement/adverification.go
vast/vastelement/inline.go
vast/vastelement/testdata/inline.xml
vast/vastelement/testdata/vast_invalid_version.xml
vast/vastelement/testdata/wrapper.xml
vast/vastelement/version.go
vast/vastelement/version_test.go
vast/vastelement/wrapper.go

This PR indtroduces  AdVerifications in vast 4.

feat(vastelement): Add vast 4 ad verification support.

---

vast/defaults/defaults.go

This PR increase the video max duration to 180s.

feat(defaults): Update the video max duration to 180s.
