Vungle/vungo

openrtb/.gitignore
openrtb/Makefile
openrtb/application.go
openrtb/bid.go
openrtb/bidrequest.go
openrtb/bidresponse.go
openrtb/device.go
openrtb/geo.go
openrtb/impression.go
openrtb/openrtbutil/client.go
openrtb/openrtbutil/client_functional_test.go
openrtb/openrtbutil/client_test.go
openrtb/openrtbutil/decoder.go
openrtb/openrtbutil/encoder.go
openrtb/openrtbutil/example_test.go
openrtb/openrtbutil/openrtbutil.go
openrtb/openrtbutil/request.go
openrtb/openrtbutil/request_test.go
openrtb/publisher.go
openrtb/regulation.go
openrtb/seatbid.go
openrtb/user.go
openrtb/video.go

- Adds `Encoder` and `Decoder` interface so that the `openrtbutil` package can support other JSON codec libraries other than the stdlib one;
- Adds `Makefile` for creating [easyjson](mailru/easyjson) marshal/unmarshal interfaces;
- Adds `easyjson` specified docstring to OpenRTB entities.
Partially fixes Vungle/jaeger#355.

feat(openrtb): Adds support for other JSON codec libraries.

---

openrtb/device.go
openrtb/regulation.go

Exchange cannot determine the real value of boolean-like fields on device level: `dnt`, `lmt`, and `js` as they may be omitted from the device. Hence, it's best for exchange to pass along the raw information instead of interpreting missing information.

fix(openrtb): Make device boolean fields: dnt, lmt, js optional

---

openrtb/export_test.go
openrtb/nobidreason.go
openrtb/nobidreason_test.go

- Refactors `NoBidReason` sections and organization;
- Adds additional no-bid reasons for Vungle DSP;
- Adds documentation for each custom no-bid reasons.
Vungle DSP can now reply with custom no-bid reasons to provide additional insights to an exchange auction

feat(openrtb): Updates custom no-bid reasons

---

openrtb/bidresponse.go
openrtb/bidresponse_test.go
openrtb/nobidreason.go

Bid response validation should accommodate validating against custom no-bid reasons.
Custom no bid reasons should pass validation.

fix(openrtb): fix BidResponse validation for no-bid reason

---

openrtb/macrosubs.go
openrtb/macrosubs_bench_test.go
openrtb/macrosubs_test.go
openrtb/settlement.go

Specify auction settlement price through an interface in MacroSubs in order to provide a price other than the bid price in the event that the auction settlement price is different from the bid price (e.g. in a second price auction).

feat(openrtb): specify auction settlement price in MacroSubs

---

openrtb/bidresponse.go
openrtb/impression.go
openrtb/openrtbtest/testutil.go
openrtb/openrtbutil/example_test.go
openrtb/openrtbutil/request_test.go

This is needed in order to supposer null as a value on price floors

Update to make price floors optional

---

openrtb/openrtbtest/testutil.go

The current version of the test for the correct number of fields in a son object does not travers nested structures
Count the number of arguments in a substructure for a full count of json fields

fix(openrtb): fix the way the tests count jsonfields

---

openrtb/macrosubs_test.go
openrtb/video.go

Allow the minduration and maxduration fields be empty if there is no valid value.
The minduration and maxduration fields can be empty if there is no valid value.

fix(openrtb): Allow the minduration and maxduration fields be empty if there is no valid value.

---

openrtb/macrosubs.go
openrtb/macrosubs_test.go

This PR fix https://vungle.atlassian.net/browse/JAE-314.
Settlement price should be precise to 9th decimal.
No impact to other services.

fix(openrtb): Settlement price should be precise to 9th decimal.

---

openrtb/vercmp/version.go
openrtb/vercmp/version_test.go

This PR adds additional comparison functions for `Version`s in the `vercmp` package. The following new methods are added:
* `func (v Version) IsAboveOrEqual(other Version) bool`
* `func (v Version) IsBelow(other Version) bool`
* `func (v Version) IsBelowOrEqual(other Version) bool`
* `func (v Version) IsEqual(other Version) bool`

feat(vercmp): add additional comparison functions

---

.travis.yml
openrtb/bid.go
openrtb/bid_test.go
openrtb/bidresponse.go
openrtb/bidresponse_test.go
openrtb/seatbid.go
openrtb/seatbid_test.go

This is useful to have so that you can preserve the original bid response but also manipulate a copy for logging purposes such as when ad markup is too large.

Adding a deep copy implementation.

---

vast/creative.go
vast/creativewrapper.go
vast/creativewrapper_test.go
vast/errors.go
vast/wrapper_test.go

Creeatives under Wrapper tags are not required and should not fail when an empty creative is placed in Wrappers.
* Add this condition to checking creatives in Wrappers `cw.Linear == nil && cw.CompanionAds == nil && cw.NonLinearAds == nil`
* Fixed typos

 fix(vast): wrapper creative check should be more lenient.

---

.travis.yml
vast/mediafile.go
vast/mediafile_test.go
vast/testdata/mediafile_without_bitrate.xml

Mediafile bitrate check was not accurate since unmarshalling integers always returns 0 as the default. Change this to a pointer to capture existence of the attribute.
* Changed `Bitrate`, `MinBitrate`, `MaxBitrate` fields to take pointers of integers.
* Fixed checks for these fields.

fix(vast): fix MediaFile tag validation.

---

openrtb/openrtbutil/client.go
openrtb/openrtbutil/client_functional_test.go
openrtb/openrtbutil/client_test.go
openrtb/openrtbutil/example_test.go
openrtb/openrtbutil/openrtbutil.go
openrtb/openrtbutil/request.go
openrtb/openrtbutil/request_test.go
vast/vastutil/unwrap.go
vast/vastutil/unwrap_test.go

This PR deprecates the use of `golang.org/x/net/context` and `golang.org/x/net/context/ctxhttp` in favor of `context`, which was added in go1.7. This change breaks backwards-compatibility with go<1.7.

refactor(*): deprecate use of x/net/context and x/net/context/ctxhttp in favor of context

---

vast/adparameters.go
vast/adparameters_test.go
vast/companion.go
vast/companion_test.go
vast/companionwrapper.go
vast/companionwrapper_test.go
vast/errors.go
vast/linear.go
vast/linear_test.go
vast/vastutil/validationresult.go

The VAST 2.0 specification does not require the adparameters field even if the tag exists.

fix(vast): There should not be a check for adparameters.

---

vast/ad_test.go
vast/inline.go
vast/inline_test.go
vast/wrapper.go
vast/wrapper_test.go

Wrappers don't require an impression tag if the unwrapped tag contains an impression.
We will need a follow up to actually validate this properly.
This should result in more impressions from wrapped VAST tags.
* Remove impression check for wrappers.

fix(vast): remove impression requirement for wrappers.

---

openrtb/application.go
openrtb/application_test.go
openrtb/bidrequest.go
openrtb/bidrequest_test.go
openrtb/deal.go
openrtb/deal_test.go
openrtb/device.go
openrtb/device_test.go
openrtb/impression.go
openrtb/impression_test.go
openrtb/privatemarketplace.go
openrtb/privatemarketplace_test.go
openrtb/publisher.go
openrtb/publisher_test.go
openrtb/regulation.go
openrtb/regulation_test.go
openrtb/user.go
openrtb/user_test.go
openrtb/video.go
openrtb/video_test.go

There are possible cases where users will need to create a copy of the bid request for customization of the extension fields. This function allows for that since it will only copy all fields except extensions.
* Creates a deep copy of the bid request that can be customized without modifying the original bid request.

 feat(openrtb): add the ability to create a deep copy of bid requests.

---

openrtb/application.go
openrtb/application_test.go
openrtb/device.go
openrtb/user.go

A fix to actually remove extensions from deep copy.

fix(openrtb): strip out extensions in deep copy.

---

openrtb/bidresponse.go
openrtb/testdata/bidresponse.json

Adds the bundle field that is required for samsung support.

feat(openrtb): accept the bundle field in bid responses

---

vast/ad_test.go
vast/inline.go
vast/inline_test.go
vast/wrapper.go
vast/wrapper_test.go

Some advertisers don't fully abide by the standard and have empty tags when passing impressions. Rather than being extremely strict with validation, we just validate that there is one valid impression. This will at least leave the responsibility to the advertiser that they are passing empty impressions and allowing us to use "valid" VAST.

feat(vast): validate that there is at least one impression tracker in the VAST

---

openrtb/regulation.go
openrtb/testdata/regulation.json

Check open-rtb spec 2.3 Section 3.2.16
https://www.iab.com/wp-content/uploads/2015/06/OpenRTB-API-Specification-Version-2-3.pdf
Regulation in openrtb 2.3.1 requires an extension field. This PR will enable it in the library.
Add `ext` field to regulation. This will help with adding GDPR fields as per https://iabtechlab.com/wp-content/uploads/2018/02/OpenRTB_Advisory_GDPR_2018-02.pdf

fix(regulation): Add extension field to regulation

---

openrtb/user.go

Check open-rtb spec 2.3 Section 3.2.13
https://www.iab.com/wp-content/uploads/2015/06/OpenRTB-API-Specification-Version-2-3.pdf
The `Id` for user object is a recommended field and not a required field. This change is to fix the openrtb implementation to make it optional.
Add `omitempty` as tag to the `id`

fix(user): fix user so that the id is not mandatory

---

vast/ad.go
vast/ad_test.go
vast/errors.go
vast/testdata/ad_no_wrapper_no_inline.xml

There is a missed check for Wrapper when it is nil. The validation would catch it, but not return.

fix(ad): minor fix in ad validation.

---

vast/inline.go
vast/inline_test.go
vast/wrapper.go
vast/wrapper_test.go

AdSystem is required per the RTB spec, but we shouldn't reject as long as a value exists in at least one level of the VAST. We should Remove the system validation. 
https://vungle.atlassian.net/browse/JAE-1444
* Remove AdSystem validation.
* update tests.

fix(vast): Remove system validation.

---

openrtb/testdata/video.json
openrtb/video.go

Check open-rtb spec 2.5 Section 3.2.7
https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf
Video in openrtb 2.5 has an extension field. This PR will enable it in the library.
- Add `ext` field to Video elements. 
- Update UT accordingly.

feat(openrtb): Add extension field to video.

---

vast/event.go
vast/event_test.go

This PR removes the validation errors for event.
https://vungle.atlassian.net/browse/PBJ-685
We should not do the strict validation. If the event type is not defined, just skipped it rather than return validate failure.
- No validate failure returns if the event type is unknown.
* The validation of event always return no error.
* Update test.

fix(vast): Remove  validation error for event.

---

openrtb/bidrequest.go
openrtb/bidrequest_test.go
openrtb/testdata/bidrequest.json

This PR adds bapp field for Openrtb bid request.
The field is a string array which represents block list of applications by their platform-specific exchange independent application identifiers. On Android, these should be bundle or package names (e.g., com.foo.mygame). On iOS, these are numeric IDs. We call it MarketID regardless of the platform in the context. 
Please refer to https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf for spec detail.
https://vungle.atlassian.net/browse/PBJ-686
If when creating the market ID, marketID black list is pass in, it should contain field after bid request constructed.
Changes
Added a new field BlockedAdvertisersByMarketID to BidRequest struct.
Updated related UT accordingly.

feat(openrtb)[PBJ-686]: Allow publishers to block certain advertising apps by MarketID

---

vast/vasttest/vasttest.go

Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?

Fix function comments based on best practices from Effective Go

---

openrtb/video.go

* Add omitempty for Video companionad and companiontype.
* Double check all new added fields for OpenRTB 2.5 and no other fields without necessary omitempty.
Issue description:
OpenX will reply 500 if bid request video contains
"companionad": null,
"companiontype": null,

fix(openrtb)[PBJ-1389]: Non-required pointer fields should be omitempty

---

vast/mediafile.go

Use filepath api instead of regex to make the code more readable.

Use filepath api instead of regex when validate uri of mediafile.

---

vast/companion.go
vast/testdata/companion.xml

CompanionClickTracking has been defined since VAST 3.0
https://www.iab.com/wp-content/uploads/2015/06/VASTv3_0.pdf 
Please see chapter 2.3.3.7 for details.

Add CompanionClickTracking support.

---

openrtb/apiframework.go

Use 7 as the value to indicate OMID support.
See more OMID support details from
https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/master/OpenRTB%20support%20for%20OMSDK.md#om-sdk-support-in-openrtb-version-20-to-25

Add  OMID API frameworks support.

---

vast/linear.go

Currently , Vungo will only keep one valid mediafile for each linear.
This PR will keep all the valid mediafiles for each linear.

update mediafile selection logic.

---

openrtb/bidresponse.go
openrtb/bidresponse_easyjson.go
openrtb/bidresponse_test.go
openrtb/export_test.go
openrtb/nobidreason.go
openrtb/openrtbutil/client_test.go
openrtb/openrtbutil/nobiderror.go
openrtb/openrtbutil/nobiderror_test.go

Change bid response nsr to pointer so it can correctly describe "no err" result. Because the default value 0 is used in spec to indicate unknown error.

feat(openrtb): Change Bid Response NoServReason Type to Pointer

---

openrtb/application_easyjson.go
openrtb/bidrequest_easyjson.go
openrtb/publisher.go
openrtb/publisher_easyjson.go
openrtb/testdata/publisher.json

Currently vungo misses the ext field for publisher object. This PR will add ext field.
Please refer to https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf 3.2.15

Add publisher ext field according to openrtb spec

---

openrtb/constants.go
openrtb/headers.go
openrtb/headers_test.go
openrtb/openrtbutil/client_functional_test.go

This PR will canonicalized the openrtb version header. By doing that we can align the  openrtb version header key with golang http lib.

feat(openrtb): Canonicalized openrtb version header

---

openrtb/nobidreason.go

This pr adds two fields in noBidReason for the two new situations of blocking by adDomain and creative ID.

feat(opentrb): Add new noBidReason for adDomain and CrID blocking

---

openrtb/bidrequest_easyjson.go
openrtb/device.go
openrtb/device_easyjson.go

Update extension fields of BidRequest and its sub structs. Change them to json.RawMessage.
Here are two reason to do that:
1: Avoid the loss of precise while unmarshal data to interface{}. The build-in json and easyjson both use the type of float64 to parse a number in json string. If it is an int64 number, some information will loss.
2: Avoid the change between interface{} and specified structs. Using json.RawMessage can make sure there is only one convert from the beginning.
This is the second part of this work, update device's extension.

refactor(openrtb): Use json.RawMessage as the extension object part3 - Device

---

vast/defaults/defaults.go
vast/vastelement/errors.go
vast/vastelement/inline_test.go
vast/vastelement/mediafile.go
vast/vastelement/mediafile_test.go
vast/vastelement/testdata/mediafile_streaming.xml
vast/vastelement/testdata/mediafile_unsupported_streaming_mediafile.xml

This PR adds support for streaming mime-types(`application/x-mpegURL`).
It also adds validation to only accept streaming ad URI with `.m3u8` suffix

feat(vast): Allow streaming mime-type.

---

vast/defaults/defaults.go

Loose the creative video length check to 120s.

fix(videolength)[PBJ-6230]: loose the video length check

---

openrtb/native/request/asset.go
openrtb/native/request/asset_easyjson.go
openrtb/native/request/data.go
openrtb/native/request/data_easyjson.go
openrtb/native/request/eventtracker.go
openrtb/native/request/eventtracker_easyjson.go
openrtb/native/request/image.go
openrtb/native/request/image_easyjson.go
openrtb/native/request/request.go
openrtb/native/request/request_easyjson.go
openrtb/native/request/title.go
openrtb/native/request/title_easyjson.go
openrtb/native/request/video.go
openrtb/native/request/video_easyjson.go
openrtb/native/response/asset.go
openrtb/native/response/asset_easyjson.go
openrtb/native/response/data.go
openrtb/native/response/data_easyjson.go
openrtb/native/response/eventtracker.go
openrtb/native/response/eventtracker_easyjson.go
openrtb/native/response/image.go
openrtb/native/response/image_easyjson.go
openrtb/native/response/link.go
openrtb/native/response/link_easyjson.go
openrtb/native/response/response.go
openrtb/native/response/response_easyjson.go
openrtb/native/response/title.go
openrtb/native/response/title_easyjson.go

The advantage of using json.RawMessage is it delays JSON decoding for just that field.
- Use json.RawMessage to get raw JSON if we need to decode it separately
- If the field is an interface, we need to assert Extension to specific types

feat(*): Use RawMessage as the extension field type.

---

vast/vastelement/linear.go
vast/vastelement/testdata/linear.xml

Liftoff can include a looping attribute on Linear in their VAST bid responses. We process this flag to allow a video to loop or not. 
User Story
-------------
https://vungle.atlassian.net/browse/VM-1863

feat(vastelement)[VM-1863]: Add looping attr for Linear

---

openrtb/bidrequest_easyjson.go
openrtb/impression_easyjson.go
openrtb/testdata/video_std.txt
openrtb/video.go
openrtb/video_easyjson.go
openrtb/videoplacementtype.go

The release of updated definitions in AdCOM List: Plcmt Subtypes – Video and a new attribute (plcmt in [Object: Video](https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/2.6.md#objectvideo)) to give publishers a way to signal video inventory in a way that more closely aligns with the updated ad format guidelines without breaking existing workstreams.
Legacy placement of video object is deprecated and proposed to remove in 2024

feat(openrtb)[PBJ-7396] Support video.plcmt in bid request

---

.travis.yml
go.mod

Updates the Go version to `1.22`
The following two places have for loops which are compiling differently:
```
[~/Developer/vungo]$ go build -gcflags=-d=loopvar=2 ./...
./audio.go:238:10: loop variable companion now per-iteration, stack-allocated
./video.go:327:10: loop variable companion now per-iteration, stack-allocated
```
In both cases the existing code can be used without modification.

chore(go mod)[SSP-186]: update go version to 1.22

---

vast/vastelement/companion.go
vast/vastelement/testdata/companion.xml

As part of implementing preloading for end cards, we need to modify the companion element to accept a optional preload attribute 
Design Doc
-----------
https://docs.google.com/document/d/1_8Y_XJNzLd0ffSIt-tYvINeLBQLZ97mN_6PPff8Vb3U/edit?tab=t.0#heading=h.1qldm0wc9qeq

feat(companion)[EF-5]: Add preload flag to Companion element

---

vast/defaults/defaults.go
vast/vastelement/mediafile_test.go
vast/vastelement/testdata/mediafile_apple_hls.xml

This PR:
- updates the supported mime types to allow Apple HLS MIME Types.
- Filtering based on platform still happens in Nautilus and Jaeger (to prevent Android devices from receiving `application/vnd.apple.mpegurl` files)

fix: add apple hls mime type
